name: Deployment

on: 
  push:
    branches:
      - main

jobs:

  deploy: 
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Staging server
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.88.28
        username: www-host
        key: ${{secrets.MIANGALY}}
        port: 22
        script: |
          cd /var/www/symfony-cs
          git status 
