name: Deployment

on: 
  push:
    branches: [main]

jobs:
  deploy: 
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Staging server
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.88.28
        username: www-deploy
        key: ${{secrets.MIANGALY}}
        port: 22
        script: |
          cd /var/www/symfony-cs
          git status 
